version: "3"
networks:
  web:
    external: true
  internal:
    external: false

services:
    testr:
        image: my-image
        labels:
            - traefik.http.routers.testr.rule=Host(`testr.devops.quinner.nl`)
            - traefik.http.routers.testr.tls=true
            - traefik.http.routers.testr.tls.certresolver=lets-encrypt
            - traefik.port=80
        networks:
            - internal
            - web
        ports:
            - 5000:5000
