FROM ubuntu:16.04

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

WORKDIR C:/Users/Leon/PycharmProjects/flaskproject


# We copy just the requirements.txt first to leverage Docker cache
COPY . .


RUN pip install -r flaskproject/requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
